Rename check_battery.py to check_battery_win10toast.py
This script still shows the current battery as a notification. Running this script manually gives this message in the Terminal, though it doesn't affect the output:

WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)